// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
            'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
         return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macOS - '
              'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for Windows - '
              'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for Linux - '
              'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }


  /// ---------------- ANDROID ----------------
  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA88VXtIT6oUWYQ6KX6APuc_b4Jvcppajs',
    appId: '1:180241236164:android:8f8aed61dafeb827604991',
    messagingSenderId: '180241236164',
    projectId: 'soulfirst-40162',
    storageBucket: 'soulfirst-40162.firebasestorage.app',
  );


  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAa3bSfK3WkrtYx8RWYoWwDTvWYhLnkgjg',
    appId: '1:180241236164:ios:e9b4537dceedcbff604991',
    messagingSenderId: '180241236164',
    projectId: 'soulfirst-40162',
    storageBucket: 'soulfirst-40162.firebasestorage.app',
    iosBundleId: 'com.socialapp.soulfirst',
  );


}
